---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
  - FaceTime
  - Music
  - Contacts
  - Reminders
  - Maps
  - Keynote
  - Pages
  - Numbers
  - Books
  - Messages
  - Photos
dockitems_persist:
- name: "Safari"
  path: "/Applications/Safari.app/"
  pos: 1
- name: "Microsoft Edge"
  path: "/Applications/Microsoft Edge.app/"
  pos: 2
- name: "Mail"
  path: "/System/Applications/Mail.app/"
  pos: 3 
- name: "Calendar"
  path: "/System/Applications/Calendar.app/"
  pos: 4
- name: "System Preferences"
  path: "/Applications/Microsoft Edge.app/"
  pos: 5
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  pos: 6
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 7
- name: "Slack"
  path: "/Applications/Slack.app/"
  pos: 8
- name: "Microsoft Teams"
  path: "/Applications/Microsoft Teams.app/"
  pos: 9
- name: "Spotify"
  path: "/Applications/Spotify.app/"
  pos: 10
- name: "TIDAL"
  path: "/Applications/TIDAL.app/"
  pos: 11

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/spike1292/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .gitconfig
  - .inputrc
  - .osx
  - .vimrc
  - .p10k.zsh

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - asimov
  - git
  - node
  - openjdk@17
  - python@3.9
  - nvm
  - pyenv
  - rbenv
  - jenv
  - ssh-copy-id
  - openssl
  - wget
  - shfmt
  - shellcheck
  - hadolint
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/services
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - 1password
  - cleanmymac
  - backblaze
  - docker
  - dropbox
  - firefox-developer-edition
  - google-chrome
  - gpg-suite
  - moom
  - licecap
  - slack
  - cyberduck
  - visual-studio-code
  - microsoft-teams
  - microsoft-office
  - microsoft-edge
  - spotify
  - tidal
  - font-fira-code
  - font-sauce-code-pro-nerd-font
  - keybase
  - caffeine
  - steam
  - lens
  - citrix-workspace

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 1440147259, name: "AdGuard for Safari" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1569813296, name: "1Password for Safari" }
mas_email: "spike1292@gmail.com"
mas_password: ""
mas_signin_dialog: false

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  # - tasks/ssh.yml
  # - tasks/gpg.yml
