---

dotfiles_repo: https://github.com/spike1292/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: essent
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - displaylink
  - 1password
  - cleanmymac
  - docker
  - dropbox
  - firefox-developer-edition
  - google-chrome
  - moom
  - slack
  - cyberduck
  - microsoft-edge
  - spotify
  - tidal
  - font-fira-code
  - font-sauce-code-pro-nerd-font
  - caffeine
  - citrix-workspace
  - notion

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 1440147259, name: "AdGuard for Safari" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1569813296, name: "1Password for Safari" }
  #- { id: '', name: "Bitwarden" }

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  - tasks/ssh.yml
  # - tasks/gpg.yml
