---
# Custom Terminal theme.
# - name: Get current Terminal profile.
#   command: defaults read com.apple.terminal 'Default Window Settings'
#   register: terminal_theme
#   changed_when: false
#   check_mode: false

- name: Ensure custom Terminal profile is added.
  copy:
    src: files/terminal/One-Dark.itermcolors
    dest: /tmp/One-Dark.itermcolors
  changed_when: false
  # when: "'One-Dark' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is added.
  command: open /tmp/One-Dark.itermcolors
  changed_when: false
  # when: "'One-Dark' not in terminal_theme.stdout"

- name: Setup oh-my-zsh with p10k
  command: "{{ dotfiles_repo_local_destination }}/.zsh-setup.bash"
  changed_when: false

- name: Replace zshrc with zshrc.p10k
  copy:
    src: "{{ dotfiles_repo_local_destination }}/.zshrc.p10k.zsh"
    dest: "~/.zshrc"
  changed_when: false

# TODO: This doesn't work in Yosemite. Consider a different solution?
# - name: Ensure custom Terminal profile is set as default.
#   command: "{{ item }}"
#   with_items:
#     - defaults write com.apple.terminal 'Default Window Settings' -string JJG-Term
#     - defaults write com.apple.terminal 'Startup Window Settings' -string JJG-Term
#   changed_when: false
#   when: "'JJG-Term' not in terminal_theme.stdout"
